services:
  postgres:
    image: postgres:alpine3.18
    container_name: todo-postgres-container
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./todo_data:/var/lib/postgresql/data
    networks:
      - todo-network

  backend:
    depends_on:
      - postgres
    build: .
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
    
    ports:
      - "4000:4000"
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  postgres_data:
